# Generated by Django 4.2 on 2023-05-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basketball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('gender_male', models.BooleanField()),
                ('captain_email', models.EmailField(max_length=254)),
                ('captain_name', models.CharField(max_length=128)),
                ('team_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cricket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('captain_email', models.EmailField(max_length=254)),
                ('captain_name', models.CharField(max_length=128)),
                ('team_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Football',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('captain_email', models.EmailField(max_length=254)),
                ('captain_name', models.CharField(max_length=128)),
                ('team_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Volleyball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('gender_male', models.BooleanField()),
                ('captain_email', models.EmailField(max_length=254)),
                ('captain_name', models.CharField(max_length=128)),
                ('team_size', models.IntegerField()),
            ],
        ),
    ]
