# Generated by Django 4.2 on 2023-05-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament_Registrations', '0004_captain_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='captain',
            name='team_size',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
