# Generated by Django 4.2 on 2023-05-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament_Registrations', '0005_captain_team_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basketball_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cricket_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Football_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Volleyball_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Basketball',
        ),
        migrations.DeleteModel(
            name='Cricket',
        ),
        migrations.DeleteModel(
            name='Football',
        ),
        migrations.DeleteModel(
            name='Volleyball',
        ),
    ]
