# Generated by Django 4.2 on 2023-05-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tournament_Registrations', '0006_basketball_team_cricket_team_football_team_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basketball_team',
        ),
        migrations.DeleteModel(
            name='Captain',
        ),
        migrations.DeleteModel(
            name='Cricket_team',
        ),
        migrations.DeleteModel(
            name='Football_team',
        ),
        migrations.DeleteModel(
            name='Volleyball_team',
        ),
    ]
