# Generated by Django 4.2 on 2023-05-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Tournament_Registrations', '0007_delete_basketball_team_delete_captain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basketball_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('team_name', models.CharField(max_length=50)),
                ('team_size', models.IntegerField()),
                ('captain_email', models.EmailField(max_length=254)),
                ('captain_name', models.CharField(max_length=128)),
                ('team', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cricket_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('team_name', models.CharField(max_length=50)),
                ('team_size', models.IntegerField()),
                ('captain_email', models.EmailField(max_length=254)),
                ('captain_name', models.CharField(max_length=128)),
                ('team', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Football_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('team_name', models.CharField(max_length=50)),
                ('team_size', models.IntegerField()),
                ('captain_email', models.EmailField(max_length=254)),
                ('captain_name', models.CharField(max_length=128)),
                ('team', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Volleyball_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField()),
                ('team_name', models.CharField(max_length=50)),
                ('team_size', models.IntegerField()),
                ('captain_email', models.EmailField(max_length=254)),
                ('captain_name', models.CharField(max_length=128)),
                ('team', models.TextField()),
            ],
        ),
    ]
